Edit first-integration, navigating, dashboard
spinningrachel/cycode pull request #1
Opened 2020-12-28 16:07 UTC by rgottesman

Wrote first draft of getting started: first integration and navigating. Started explaining the dashboard in more detail under navigating, but moved it to dashboard.

2020-12-28 17:54 UTC, spinningrachel requested changes
@rgottesman 
Awesome start. Please go through my comments and fix up based on suggestions and then you can merge and commit.

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +After logging in, you are taken to the dashboard. To get to the dashboard when you are in another area of Cycode, click on the Cycode or dashboard icons. Along the top of the dashboard there are:
```suggestion
Once you've logged in, the dashboard loads. 

To navigate to the dashboard when you are in another area of Cycode, click the Cycode icon from the top, or click <enter icon here> from the left side panel. 

The dashboard appears similar to the following image:
<enter image of dashboard. obfuscate personal and company information>

Along the top of the dashboard, find these cards:  
```

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +- users: anyone with access to the pipeline
@rgottesman  Since all of these are parts of the screen, they are proper names and should be capitalized.

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +- organizations: ?
these are the organizations managed from the third-party app - hierarchically, they are above the repos, teams and contributors.

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +Click on them to see more detailes and manage them.
```suggestion
Click any of these cards to see more details and manage them.  Cycode redirects you to the relevant area. 
```

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +Below that, there are two lists:
```suggestion
Below these cards, there are two lists:  
```

@rgottesman isn't specific since it's far away from the initial reference of what you're talking about.

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +-  act: notification of weaknesses in your credentials that you need to deal with in the near future
you need to deal with in the near future  - not urgent enough; you can use the word "act" - for example you need to act on quickly

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +- improve: notification of general improvements you need to make for security
```suggestion
- improve: notification of best practices you should implement in order to improve your security posture
```

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +Below that, there are three graphs or charts showing alerts:
```suggestion
Below that, there are three graphs or charts showing alerts:  
```

@rgottesman instead of Below that over and over again, add number stamps to the original image of the dashboard (that I suggested you add) and then insert those numbers as images next to the description of each part (like I demo'd for you today when I was showing you how to insert images)

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +- alerts by type:  a chart that groups current alerts by type. Clicking on a type will take you to a full list of those alerts.
```suggestion
- alerts by type:  a chart that groups current alerts by type. Click any of the types to navigate to the full list of the relevant alerts.
```

@rgottesman try to avoid gerunds

2020-12-28 17:54 UTC, spinningrachel commented on docs/dashboard.md
> +At the bottom of the page, there are three sections:
@rgottesman again - number stamps I think are preferable for the layout

also - for all of the lists, i just realized you're using colons where i would have used dashes - if you could default to dashes that would be great b/c i won't ever remember to change my habits at this stage in the game 

it probably feels awkward to you b/c you're using dashes in the markdown for bullets - but remember the bullets convert to nice GUI bullets in teh output :)

2020-12-28 17:54 UTC, spinningrachel commented on docs/first-integration.md
> +Now that you have logged in, you can integrate GitHub. Integrating Github enables Cycode to:
Now that => once you've

```suggestion
Once you've logged in, you need to integrate with at least one source in order to start measuring your security posture. 

Let's start by integrating GitHub. 

Integrating Github enables Cycode to:  
```

@rgottesman remember this is Getting Started - so this is why i've added this unique language here.

2020-12-28 17:54 UTC, spinningrachel commented on docs/first-integration.md
> +1. Navigate to settings.
All parts of the screens should be capitalized and bold. settings shoudl be **Settings** for example. I'll let you fix the other instances across the text.

2020-12-28 17:54 UTC, spinningrachel commented on docs/first-integration.md
> +2. In settings, click on integration.
@rgottesman no need for prepositions b/c they're proper nouns (see the style guide). So: Click **Integration**. I'll let you you fix up the other instances across the text.

2020-12-30 06:44 UTC, rgottesman commented on docs/dashboard.md
> +At the bottom of the page, there are three sections:
@spinningrachel Which dash should I use? Hyphen, en dash, or em dash?

2020-12-30 07:01 UTC, spinningrachel commented on docs/dashboard.md
> +At the bottom of the page, there are three sections:
@rgottesman in markdown for our use cases, you can always use just the regular hyphen and expect it to format correctly in the output

2020-12-30 11:34 UTC, merged