Personal.md
spinningrachel/cycode pull request #2
Opened 2020-12-30 17:11 UTC by rgottesman

Update personal settings page

2020-12-30 19:04 UTC, spinningrachel requested changes

2020-12-30 19:04 UTC, spinningrachel commented on docs/personal.md
> +1. Use your phone to scan the QR code that appears on the screen.
```suggestion
1. From the Personal Settings area, in the My Profile pane click MFA. 
    
    The Multi-Factor Authentication window loads, similar to the following: 
    
    <insert mfa.png (I already added it to the folder)>
    
2. Toggle the button to enable MFA.

```

2020-12-30 19:04 UTC, spinningrachel commented on docs/personal.md
> +2. Enter the 6-digit code from your authenticator app.
```suggestion
2. From Cycode, enter the 6-digit code.
```

2020-12-30 19:04 UTC, spinningrachel commented on docs/personal.md
> +	If you lose your phone, the recovery code enables you to log in.
```suggestion
	The recovery code enables you to log in if you lose your phone, 
```

2020-12-30 19:04 UTC, spinningrachel commented on docs/personal.md
> +3. Save your recovery code.
```suggestion
3. Save your recovery code in a safe place.
```

2020-12-30 19:13 UTC, spinningrachel requested changes

2020-12-30 19:13 UTC, spinningrachel commented on docs/personal.md
Enter an explanation how to navigate to this area.

2020-12-30 19:13 UTC, spinningrachel commented on docs/personal.md
> +1. Click **Create New**.
@rgottesman try adding results and images to the rest of the processes

2020-12-31 07:03 UTC, rgottesman commented on docs/personal.md
> +1. Click **Create New**.
The personal access token page looks different when there aren't any tokens created yet. Can I delete the token you created, or should I wait until we get a clean account?

2020-12-31 07:05 UTC, rgottesman commented on docs/personal.md
> +To change your password, enter your current password and then enter a new one.
Is an authenticator app necessary to change passwords also? Or just for MFA (in which case the prerequisite would be in that section)?

2021-01-03 07:30 UTC, rgottesman commented on docs/personal.md
> +To change your password, enter your current password and then enter a new one.
@spinningrachel ?

2021-01-04 07:48 UTC, merged